config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  resources :boards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :width, presence: true, numericality: { greater_than: 0 }
  validates :height, presence: true, numericality: { greater_than: 0 }
  validates :mines, presence: true, numericality: { greater_than_or_equal_to: 0 }

  serialize :cells, Array

  after_save :generate_board

  # This method is used to generate the board for given width and height and it will randomly set the mines on the generated board.
  def generate_board
    board = Array.new(height) { Array.new(width, false) }
  
    mines.times do
      row = nil
      col = nil
  
      loop do
        row = rand(height)
        col = rand(width)
        break unless board[row][col]
      end
  
      board[row][col] = true
    end
    update_column(:cells, board)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boards, dependent: :destroy

  accepts_nested_attributes_for :boards

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  
  # This will list all the boards 
  def index
    if params[:view_all].present? && params[:view_all] == "true" 
      @boards = Board.all.order(created_at: :desc)
    else   
      @boards = Board.all.order(created_at: :desc).limit(10)
    end

  end

  def new
    @user = User.new
    @user.boards.build
  end

  # This method will first create a user with given email and then it will generate board for that user.
  def create
    @user = User.find_or_initialize_by(email: board_params[:email])
    if @user.update(board_params)
      @board = @user.boards.last
      redirect_to board_path(@board.id)
    else
      render :new
    end
  end

  # This will display the board details.
  def show
    @board = Board.find(params[:id])
  end

  private 
  def board_params 
    params.require(:user).permit(:email, boards_attributes: [:name, :width, :height, :mines])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board_visual.html.erb
<% @board.cells.each_with_index do |row, i| %>
  <% row.each_with_index do |cell, j| %>
    <% if cell %>
      <span  class="board-cell mine" data-row="<%= i %>" data-col="<%= j %>">
        <%= image_tag 'bomb.png', class: "mine-img" %>
      </span>
    <% else %>
      <span class="board-cell empty" data-row="<%= i %>" data-col="<%= j %>"></span>
    <% end %>
  <% end %>
  <br>
<% end %>

<style>
.board-cell {
    display: inline-block;
    width: 40px;
    height: 40px;
    border: 1px solid #ccc;
    text-align: center;
    line-height: 40px;
    font-size: 24px;
    cursor: pointer;
}

.board-cell.empty {
  background-color: black;
}

.board-cell.mine {
  position:relative;
}

.mine-img {
  width: 40px;
  height: 40px;
  display: grid;
}

</style>

app/views/boards/create.html.erb
<h1>Boards#create</h1>
<p>Find me in app/views/boards/create.html.erb</p>

app/views/boards/index.html.erb
<h1>Minesweeper List</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= link_to board.name, board_path(board.id) %></td>
        <td><%= board.user.email %></td>
        <td><%= board.created_at.strftime("%Y-%m-%d") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div className="modal-footer">
  <button><%= link_to 'View All Board', root_path(view_all: true) %></button>
  <button><%= link_to 'Generate New Board', new_board_path %></button>
</div> 


<style>
  table.table {
    border-collapse: collapse;
  }
  table.table th, table.table td {
    border: 1px solid black;
    padding: 8px;
  }
</style>

app/views/boards/new.html.erb
<div>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
      <p class ="errors"><%= message %></p>
    <% end %>
  <% end %>
</div>  

<h1>Create a Minesweeper Board</h1>

<div class="small-row">
  <%= form_for @user, url: boards_path, data: { turbo:false } do |form| %>
    <%= form.fields_for :boards do |ff| %>
      <div class="form-group">
        <label for="formGroupExampleInput">Enter name:</label>
        <%= ff.text_field :name %>
      </div>

      <div class="form-group">
        <label for="formGroupExampleInput">Enter email:</label>
        <%= form.text_field :email %>
      </div>

      <div class="form-group">
        <label for="formGroupExampleInput2">Enter width:</label>
        <%= ff.number_field :width %>
      </div>
      <div class="form-group">
        <label for="formGroupExampleInput2">Enter height:</label>
        <%= ff.number_field :height %>
      </div>
      <div class="form-group">
        <label for="formGroupExampleInput2">Enter mines:</label>
        <%= ff.number_field :mines %>
      </div>
    <% end %>
    <%= form.submit "Generate Board", class: "submit-button" %>
  <% end %>
</div>

<style>
  .errors{ color: red; }
  .small-row{width: 50%;}
  .submit-button{ margin-top: 12px; }

  form {
    border: 1px solid black;
    padding: 10px;
  }
  .form-group {
    margin-bottom: 10px;
  }
  label {
    display: block;
    margin-bottom: 5px;
  }
  input[type="text"],
  input[type="number"] {
    width: 50%;
    padding: 5px;
  }
</style>

app/views/boards/show.html.erb
<h1>Board name: <%= @board.name %></h1>
<p>Generated by: <%= @board.user.email %></p>

<div class="minesweeper-board">
  <%= render 'board_visual', board: @board %>
</div>

<%= link_to 'Back to All Boards', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Minesweeper board</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
      </ul>
    </div>
  </div>
</nav>